"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export default function AccountRegistrationForm() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, password }) }); const data = await response.json(); setSuccess(response.ok); setMessage(data.message); }
  return <form onSubmit={submit} className="soft-panel mx-auto max-w-md p-6 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-royal">Akun anggota</p><h1 className="mt-2 text-3xl font-bold text-navy-deep">Daftar akun login</h1><p className="mt-2 text-sm leading-6 text-slate-600">Akun baru harus diverifikasi admin sebelum dapat digunakan untuk login.</p><label className="mt-6 block text-sm font-medium">Nama lengkap<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-3" /></label><label className="mt-4 block text-sm font-medium">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-3" /></label><label className="mt-4 block text-sm font-medium">Kata sandi<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-3" /></label>{message && <p className={`mt-4 text-sm ${success ? "text-emerald-700" : "text-red-700"}`}>{message}</p>}<button className="mt-6 rounded-full bg-navy px-5 py-3 text-sm font-semibold text-white">Kirim pendaftaran akun</button><p className="mt-6 text-center text-sm text-slate-600">Sudah memiliki akun? <Link href="/login" className="font-semibold text-blue-royal">Login</Link></p></form>;
}
