import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function DashboardPage() {
  const session = await getSession(); if (!session || session.role !== "SCHOOL") redirect("/login");
  const user = await prisma.user.findUnique({ where: { id: session.id }, select: { name: true, email: true, school: { include: { foundation: true } } } }); if (!user) redirect("/login");
  const registrations = await prisma.schoolRegistration.findMany({ where: { email: user.email }, select: { registrationNumber: true, name: true, status: true, rejectionReason: true, updatedAt: true }, orderBy: { updatedAt: "desc" }, take: 10 });
  return <div className="section-shell py-12 sm:py-16"><div className="soft-panel p-5 sm:p-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-royal">Dashboard anggota</p><h1 className="mt-2 text-2xl font-bold text-navy-deep sm:text-3xl">Selamat datang, {user.name}</h1><p className="mt-2 text-sm text-slate-600">Notifikasi keputusan pendaftaran sekolah Anda tersedia di bawah ini.</p>{user.school && <div className="mt-6 rounded-2xl bg-blue-light p-4 text-sm text-navy-deep"><b>Sekolah terhubung:</b> {user.school.name}{user.school.foundation ? ` · ${user.school.foundation.name}` : ""}</div>}<section className="mt-8"><h2 className="text-xl font-bold text-navy-deep">Notifikasi pendaftaran sekolah</h2><div className="mt-4 space-y-3">{registrations.length ? registrations.map((registration) => <article key={registration.registrationNumber} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p className="font-semibold text-navy-deep">{registration.name}</p><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${registration.status === "APPROVED" ? "bg-emerald-100 text-emerald-700" : registration.status === "REJECTED" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{registration.status === "APPROVED" ? "Diterima" : registration.status === "REJECTED" ? "Ditolak" : "Menunggu verifikasi"}</span></div><p className="mt-1 text-sm text-slate-600">Nomor: {registration.registrationNumber}</p>{registration.rejectionReason && <p className="mt-2 text-sm text-red-700">Alasan penolakan: {registration.rejectionReason}</p>}</article>) : <p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">Belum ada pendaftaran sekolah dengan email akun ini.</p>}</div></section></div></div>;
}
